Libraries

In [31]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

Dataset

In [32]:
df = pd.read_csv("/content/ResumeDataSet.csv")

df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

NLP Preprocessing

In [35]:
import nltk
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

def preprocess(text):
  text = text.lower()
  words = word_tokenize(text)
  words = [w for w in words if w.isalnum()] #remove symbols
  words = [w for w in words if w not in stop_words]
  return " ".join(words)

df['cleaned_resume'] = df['Resume'].apply(preprocess)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Job Description

In [37]:
job_description = """
Looking for a data scientist with skills in python, machine learning,
deep learning, pandas, numpy, data analysis, and statistics.
"""

job_description = preprocess(job_description)

Filter by Category

In [43]:
filtered_df = df[df['Category'] == "Data Science"].copy()

all_texts = filtered_df['cleaned_resume'].tolist() + [job_description]

tfidf_matrix = tfidf.fit_transform(all_texts)

job_vector = tfidf_matrix[-1]

scores = cosine_similarity(tfidf_matrix[:-1], job_vector)

filtered_df['score'] = scores * 100

filtered_df = filtered_df.sort_values(by='score', ascending=False)

filtered_df[['Category', 'score']].head(10)

        Category      score
7   Data Science  20.684568
37  Data Science  20.684568
27  Data Science  20.684568
17  Data Science  20.684568
16  Data Science  19.947308
6   Data Science  19.947308
36  Data Science  19.947308
26  Data Science  19.947308
38  Data Science  18.102838
28  Data Science  18.102838